package com.loganmartlew.rangework.shared.usecase

import com.loganmartlew.rangework.shared.model.Club
import com.loganmartlew.rangework.shared.model.ClubCategory
import com.loganmartlew.rangework.shared.model.EnabledClubCount
import com.loganmartlew.rangework.shared.model.NextMoveState
import com.loganmartlew.rangework.shared.model.PracticeInstruction
import com.loganmartlew.rangework.shared.model.PracticeInstructionDraft
import com.loganmartlew.rangework.shared.model.PracticeSession
import com.loganmartlew.rangework.shared.model.PracticeSessionItem
import com.loganmartlew.rangework.shared.model.PracticeUnit
import com.loganmartlew.rangework.shared.model.PracticeUnitDraft
import com.loganmartlew.rangework.shared.model.RecentItem
import com.loganmartlew.rangework.shared.model.estimateSessionDurationMinutes
import com.loganmartlew.rangework.shared.model.recentItems
import com.loganmartlew.rangework.shared.model.resolveNextMoveState
import com.loganmartlew.rangework.shared.model.sessionsUsingUnit
import com.loganmartlew.rangework.shared.repository.PracticeSessionRepository
import com.loganmartlew.rangework.shared.repository.PracticeUnitRepository
import kotlinx.datetime.Instant
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFalse
import kotlin.test.assertIs
import kotlin.test.assertNotEquals
import kotlin.test.assertTrue

class Stage03DataEnablerTest {

    // ── PracticeLibrary.duplicateUnit ────────────────────────────────────

    @Test
    fun duplicateUnitProducesIndependentCopyWithNoSharedReferences() = kotlinx.coroutines.test.runTest {
        val original = makeUnit(
            id = "unit-original",
            title = "Chip shots",
            notes = "Tight lies only",
            focus = "Weight forward",
            defaultClubCode = "PW",
            instructions = listOf(
                PracticeInstruction(id = "instr-1", order = 1, text = "Grip down", ballCount = 10),
                PracticeInstruction(id = "instr-2", order = 2, text = "Low finish", ballCount = 20),
            ),
        )
        val repo = StubPracticeUnitRepository(existing = original)
        val library = com.loganmartlew.rangework.shared.library.DefaultPracticeLibrary(
            unitRepository = repo,
            sessionRepository = StubPracticeSessionRepository(),
        )

        val copy = library.duplicateUnit("unit-original")

        assertNotEquals("unit-original", copy.id, "Duplicate must have a new id")
        assertEquals("Chip shots", copy.title)
        assertEquals("Tight lies only", copy.notes)
        assertEquals("Weight forward", copy.focus)
        assertEquals("PW", copy.defaultClubCode)
        assertEquals(2, copy.instructions.size)
        assertEquals("Grip down", copy.instructions[0].text)
        assertEquals(10, copy.instructions[0].ballCount)
        assertEquals("Low finish", copy.instructions[1].text)
        assertEquals(20, copy.instructions[1].ballCount)

        // Instructions get new ids (generated by the repository)
        assertTrue(copy.instructions.none { it.id == "instr-1" || it.id == "instr-2" })
    }

    // ── estimateSessionDurationMinutes ───────────────────────────────────────

    @Test
    fun estimateDurationReturnsZeroWhenNoBallsInSession() {
        val session = makeSession(items = emptyList())
        assertEquals(0, estimateSessionDurationMinutes(session, emptyMap()))
    }

    @Test
    fun estimateDurationRoundsToNearestMinuteForSmallBallCount() {
        // Unit with 4 balls; session repeats it once → 4 balls × 15s = 60s = 1 min
        val unit = makeUnit(
            instructions = listOf(PracticeInstruction(id = "i1", order = 1, text = "Hit", ballCount = 4)),
        )
        val session = makeSession(
            items = listOf(makeSessionItem(unitId = unit.id, repeatCount = 1)),
        )
        assertEquals(1, estimateSessionDurationMinutes(session, mapOf(unit.id to unit)))
    }

    @Test
    fun estimateDurationScalesCorrectlyForLargeBallCount() {
        // Unit with 60 balls; session repeats it 3x → 180 balls × 15s = 2700s = 45 min
        val unit = makeUnit(
            instructions = listOf(PracticeInstruction(id = "i1", order = 1, text = "Hit", ballCount = 60)),
        )
        val session = makeSession(
            items = listOf(makeSessionItem(unitId = unit.id, repeatCount = 3)),
        )
        assertEquals(45, estimateSessionDurationMinutes(session, mapOf(unit.id to unit)))
    }

    @Test
    fun estimateDurationIgnoresSessionItemsWithNoMatchingUnit() {
        val session = makeSession(
            items = listOf(makeSessionItem(unitId = "missing-unit", repeatCount = 5)),
        )
        assertEquals(0, estimateSessionDurationMinutes(session, emptyMap()))
    }

    // ── EnabledClubCount ─────────────────────────────────────────────────────

    @Test
    fun enabledClubCountMatchesEnabledSetInCatalog() {
        val catalog = listOf(
            makeClub("driver"), makeClub("three_wood"), makeClub("five_iron"), makeClub("putter"),
        )
        val enabled = setOf("driver", "putter")

        val count = EnabledClubCount.from(catalog, enabled)

        assertEquals(2, count.enabled)
        assertEquals(4, count.total)
    }

    @Test
    fun enabledClubCountReturnsZeroEnabledWhenNoneEnabled() {
        val catalog = listOf(makeClub("driver"), makeClub("putter"))
        val count = EnabledClubCount.from(catalog, emptySet())
        assertEquals(0, count.enabled)
        assertEquals(2, count.total)
    }

    @Test
    fun enabledClubCountMatchesTotalWhenAllEnabled() {
        val catalog = listOf(makeClub("driver"), makeClub("putter"))
        val count = EnabledClubCount.from(catalog, setOf("driver", "putter"))
        assertEquals(2, count.enabled)
        assertEquals(2, count.total)
    }

    @Test
    fun enabledClubCountIgnoresEnabledCodesNotInCatalog() {
        val catalog = listOf(makeClub("driver"))
        val count = EnabledClubCount.from(catalog, setOf("driver", "phantom_club"))
        assertEquals(1, count.enabled)
        assertEquals(1, count.total)
    }

    // ── recentItems ──────────────────────────────────────────────────────────

    @Test
    fun recentItemsReturnsMostRecentFirst() {
        val older = makeUnit(id = "u-old", updatedAt = Instant.parse("2026-06-10T00:00:00Z"))
        val newer = makeUnit(id = "u-new", updatedAt = Instant.parse("2026-06-15T00:00:00Z"))

        val result = recentItems(listOf(older, newer), emptyList())

        assertEquals("u-new", result.first().id)
        assertEquals("u-old", result.last().id)
    }

    @Test
    fun recentItemsMixesUnitsAndSessionsOrderedByUpdatedAt() {
        val unit = makeUnit(id = "u1", updatedAt = Instant.parse("2026-06-14T00:00:00Z"))
        val session = makeSession(id = "s1", updatedAt = Instant.parse("2026-06-15T00:00:00Z"))

        val result = recentItems(listOf(unit), listOf(session))

        assertIs<RecentItem.Session>(result[0])
        assertIs<RecentItem.Unit>(result[1])
    }

    @Test
    fun recentItemsBoundedByLimit() {
        val base = Instant.parse("2026-06-01T00:00:00Z")
        val units = (0 until 10).map { i ->
            makeUnit(
                id = "u$i",
                updatedAt = Instant.fromEpochSeconds(base.epochSeconds + i * 3600),
            )
        }

        val result = recentItems(units, emptyList(), limit = 5)

        assertEquals(5, result.size)
    }

    @Test
    fun recentItemsReturnsEmptyWhenNoUnitsOrSessions() {
        val result = recentItems(emptyList(), emptyList())
        assertTrue(result.isEmpty())
    }

    // ── sessionsUsingUnit ───────────────────────────────────────────────────

    @Test
    fun sessionsUsingUnitReturnsSessionsReferencingUnit() {
        val unit = makeUnit(id = "unit-target")
        val sessions = listOf(
            makeSession(id = "session-1", items = listOf(makeSessionItem(unitId = unit.id))),
            makeSession(id = "session-2", items = listOf(makeSessionItem(unitId = "other-unit"))),
            makeSession(id = "session-3", items = listOf(makeSessionItem(unitId = unit.id))),
        )

        val result = sessionsUsingUnit(unit.id, sessions)

        assertEquals(listOf("session-1", "session-3"), result.map { it.id })
    }

    @Test
    fun sessionsUsingUnitReturnsEmptyWhenUnitIsUnused() {
        val sessions = listOf(
            makeSession(id = "session-1", items = listOf(makeSessionItem(unitId = "other-unit"))),
        )

        val result = sessionsUsingUnit("unit-target", sessions)

        assertTrue(result.isEmpty())
    }

    @Test
    fun sessionsUsingUnitReturnsSessionOnceForMultipleReferences() {
        val session = makeSession(
            id = "session-1",
            items = listOf(
                makeSessionItem(unitId = "unit-target"),
                makeSessionItem(unitId = "unit-target"),
            ),
        )

        val result = sessionsUsingUnit("unit-target", listOf(session))

        assertEquals(listOf("session-1"), result.map { it.id })
    }

    // ── resolveNextMoveState ─────────────────────────────────────────────────

    @Test
    fun nextMoveStateIsNoUnitsWhenNoUnitsExist() {
        val state = resolveNextMoveState(emptyList(), emptyList())
        assertIs<NextMoveState.NoUnits>(state)
    }

    @Test
    fun nextMoveStateIsUnitsNoSessionsWhenUnitsExistButNoSessions() {
        val state = resolveNextMoveState(listOf(makeUnit()), emptyList())
        assertIs<NextMoveState.UnitsNoSessions>(state)
    }

    @Test
    fun nextMoveStateIsBothWhenUnitsAndSessionsExistWithNoRecentSave() {
        val state = resolveNextMoveState(listOf(makeUnit()), listOf(makeSession()))
        assertIs<NextMoveState.Both>(state)
    }

    @Test
    fun nextMoveStateIsResumeEditingUnitWhenLastSavedUnitIdPresent() {
        val state = resolveNextMoveState(
            units = listOf(makeUnit(id = "u1")),
            sessions = listOf(makeSession()),
            lastSavedUnitId = "u1",
        )
        val resume = assertIs<NextMoveState.ResumeEditing>(state)
        assertEquals("u1", resume.entityId)
        assertTrue(resume.isUnit)
        assertEquals("Test unit", resume.entityName)
    }

    @Test
    fun nextMoveStateIsResumeEditingSessionWhenLastSavedSessionIdPresent() {
        val state = resolveNextMoveState(
            units = listOf(makeUnit()),
            sessions = listOf(makeSession(id = "s1")),
            lastSavedSessionId = "s1",
        )
        val resume = assertIs<NextMoveState.ResumeEditing>(state)
        assertEquals("s1", resume.entityId)
        assertFalse(resume.isUnit)
        assertEquals("Test session", resume.entityName)
    }

    @Test
    fun nextMoveStateIsNoUnitsEvenWhenLastSavedUnitIdPresent() {
        // No units in list → NoUnits takes priority
        val state = resolveNextMoveState(
            units = emptyList(),
            sessions = emptyList(),
            lastSavedUnitId = "u1",
        )
        assertIs<NextMoveState.NoUnits>(state)
    }

    @Test
    fun nextMoveStateFallsBackToBothWhenLastSavedEntityIsMissing() {
        val state = resolveNextMoveState(
            units = listOf(makeUnit(id = "u1")),
            sessions = listOf(makeSession(id = "s1")),
            lastSavedUnitId = "missing-unit",
        )

        assertIs<NextMoveState.Both>(state)
    }
}

// ── Helpers ──────────────────────────────────────────────────────────────────

private val BASE_INSTANT = Instant.parse("2026-06-15T00:00:00Z")

private fun makeUnit(
    id: String = "unit-1",
    title: String = "Test unit",
    notes: String? = null,
    focus: String? = null,
    defaultClubCode: String? = null,
    instructions: List<PracticeInstruction> = emptyList(),
    updatedAt: Instant = BASE_INSTANT,
) = PracticeUnit(
    id = id,
    title = title,
    instructions = instructions,
    notes = notes,
    focus = focus,
    defaultClubCode = defaultClubCode,
    createdAt = BASE_INSTANT,
    updatedAt = updatedAt,
)

private fun makeSession(
    id: String = "session-1",
    name: String = "Test session",
    items: List<PracticeSessionItem> = emptyList(),
    updatedAt: Instant = BASE_INSTANT,
) = PracticeSession(
    id = id,
    name = name,
    items = items,
    createdAt = BASE_INSTANT,
    updatedAt = updatedAt,
)

private fun makeSessionItem(
    unitId: String = "unit-1",
    repeatCount: Int = 1,
) = PracticeSessionItem(
    id = "item-${unitId}",
    practiceUnitId = unitId,
    order = 1,
    repeatCount = repeatCount,
)

private fun makeClub(code: String) = Club(
    code = code,
    displayName = code,
    category = ClubCategory.IRON,
    sortOrder = 1,
)

private class StubPracticeUnitRepository(
    private val existing: PracticeUnit,
) : PracticeUnitRepository() {
    private val store = mutableMapOf(existing.id to existing)

    override suspend fun list(): List<PracticeUnit> = store.values.toList()

    override suspend fun get(id: String): PracticeUnit? = store[id]

    override suspend fun persist(validated: PracticeUnitDraft, unitId: String?): PracticeUnit {
        val newId = unitId ?: "generated-${store.size + 1}"
        val saved = PracticeUnit(
            id = newId,
            title = validated.title,
            instructions = validated.instructions.mapIndexed { idx, d ->
                PracticeInstruction(
                    id = "gen-instr-${newId}-$idx",
                    order = d.order,
                    text = d.text,
                    ballCount = d.ballCount,
                )
            },
            notes = validated.notes,
            focus = validated.focus,
            defaultClubCode = validated.defaultClubCode,
            createdAt = BASE_INSTANT,
            updatedAt = BASE_INSTANT,
        )
        store[newId] = saved
        return saved
    }

    override suspend fun delete(id: String) {
        store.remove(id)
    }
}

private class StubPracticeSessionRepository : PracticeSessionRepository() {
    override suspend fun list(): List<PracticeSession> = emptyList()

    override suspend fun listArchived(): List<PracticeSession> = emptyList()

    override suspend fun get(id: String): PracticeSession? = null

    override suspend fun persist(validated: com.loganmartlew.rangework.shared.model.PracticeSessionDraft, sessionId: String?): PracticeSession {
        error("Not implemented in stub")
    }

    override suspend fun setArchived(id: String, archivedAt: kotlinx.datetime.Instant?): PracticeSession {
        error("Not implemented in stub")
    }

    override suspend fun delete(id: String) = Unit
}
